services:
  postgres:
    image: postgres:16
    container_name: interns-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interns
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  server:
    build:
      context: ../
      dockerfile: src/server/InternshipRecords.Web/Dockerfile
    container_name: interns-server
    depends_on:
      - postgres
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=interns;Username=postgres;Password=postgres"
    ports:
      - "5001:80"
    restart: always

  client:
    build:
      context: ../
      dockerfile: src/client/InternshipRecords.Client/Dockerfile
    container_name: interns-client
    depends_on:
      - server
    ports:
      - "5000:80"
    restart: always

volumes:
  postgres_data:
